app/cart/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views


app_name = 'cart'


urlpatterns = [
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('account/', include('account.urls', namespace='account')),
    path('wishlist/', include('wishlist.urls', namespace='wishlist'))
]

app/wishlist/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views


app_name = 'wishlist'


urlpatterns = [
    path('', views.ViewWishList.as_view(), name='wishlist'),
    path('add/<int:product_id>', views.WishlistCreate.as_view(), name='wishlist_add'),
    path('remove/<int:product_id>', views.WishlistDelete.as_view(), name='wishlist_remove')
]




if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/wishlist/models.py
from django.contrib.auth.models import User
from django.db import models

from shop.models import Product


class Wishlist(models.Model):
    user = models.ForeignKey(User, related_name='users', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='products', on_delete=models.CASCADE)


    class Meta:
        ordering = ('user',)

app/wishlist/forms.py
from django import forms

from wishlist.models import Wishlist


class WishlistAddProductForm(forms.Form):
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

app/wishlist/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
# Create your views here.
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import ListView

from shop.models import Product
from shop.templatetags.news_tags import get_amount_product
from wishlist.models import Wishlist


class WishlistCreate(View):
    model = Wishlist

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        product = get_object_or_404(Product, id=self.kwargs['product_id'], available=True)
        if not Wishlist.objects.filter(user=self.request.user, product=product):
            Wishlist.objects.create(user=self.request.user, product=product)
        return HttpResponseRedirect(self.request.META.get('HTTP_REFERER'))


class WishlistDelete(View):
    model = Wishlist

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        product = get_object_or_404(Product, id=self.kwargs['product_id'], available=True)
        Wishlist.objects.filter(user=self.request.user, product=product).delete()
        return HttpResponseRedirect(reverse("wishlist:wishlist"))


class ViewWishList(ListView):
    model = Wishlist
    template_name = 'wishlist/wishlist.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if request.method.lower() in self.http_method_names:
            handler = getattr(
                self, request.method.lower(), self.http_method_not_allowed
            )
        else:
            handler = self.http_method_not_allowed
        return handler(request, *args, **kwargs)

    def get_queryset(self):
        return Wishlist.objects.filter(user=self.request.user)

app/wishlist/templates/wishlist/wishlist.html
{% extends "shop/base.html" %}
{% load static %}
{% block content %}
    <div class="section">
        <!-- container -->
        <div class="container">
            <div class="col-md-12">
                <div class="row">
                    <div class="products-tabs">
                        <!-- tab -->
                        <div id="tab1" class="tab-pane active">
                            <div class="products-slick" data-nav="#slick-nav-1">
                                <!-- product -->
                                {% for wishlist in object_list %}
                                    <div class="product">
                                    <form action="{% url 'wishlist:wishlist_remove' wishlist.product.id %}" method="post">
                                        {% csrf_token %}
                                        <button class="delete"><i class="fa fa-close"></i></button>
                                        </form>
                                        <div class="product-img">
                                            <img src="{{ wishlist.product.image.url }}" alt="" class="Image">
                                            <div class="product-label">
                                                <span class="sale">-30%</span>
                                                <span class="new">NEW</span>
                                            </div>
                                        </div>
                                        <div class="product-body">
                                            <p class="product-category">{{ wishlist.product.catecory }}</p>
                                            <h3 class="product-name"><a
                                                    href="{{ wishlist.product.get_absolute_url }}">{{ product.name }}</a>
                                            </h3>
                                            <h4 class="product-price">{{ wishlist.product.price }}
                                                <del class="product-old-price">$990.00</del>
                                            </h4>
                                            <div class="product-rating">
                                                {% if wishlist.product.get_rating >= 1 %}
                                                    <i class="fa fa-star"></i>
                                                {% else %}
                                                    <i class="fa fa-star-o empty"></i>
                                                {% endif %}
                                                {% if wishlist.product.get_rating >= 2 %}
                                                    <i class="fa fa-star"></i>
                                                {% else %}
                                                    <i class="fa fa-star-o empty"></i>
                                                {% endif %}
                                                {% if wishlist.product.get_rating >= 3 %}
                                                    <i class="fa fa-star"></i>
                                                {% else %}
                                                    <i class="fa fa-star-o empty"></i>
                                                {% endif %}
                                                {% if wishlist.product.get_rating >= 4 %}
                                                    <i class="fa fa-star"></i>
                                                {% else %}
                                                    <i class="fa fa-star-o empty"></i>
                                                {% endif %}
                                                {% if wishlist.product.get_rating == 5 %}
                                                    <i class="fa fa-star"></i>
                                                {% else %}
                                                    <i class="fa fa-star-o empty"></i>
                                                {% endif %}
                                            </div>
                                            <div class="product-btns">
                                                <button class="add-to-compare"><i class="fa fa-exchange"></i><span
                                                        class="tooltipp">add to compare</span></button>
                                                <button class="quick-view"><i class="fa fa-eye"></i><span
                                                        class="tooltipp">quick view</span>
                                                </button>
                                            </div>
                                        </div>
                                        <div class="add-to-cart">
                                            <form action="{% url 'cart:cart_add' wishlist.product.id %}" method="post">
                                                {{ cart_product_form }}
                                                {% csrf_token %}
                                                <button class="add-to-cart-btn">Add<i class="fa fa-shopping-cart"></i>
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                {% endfor %}
                                <!-- /product -->
                            </div>
                            <div id="slick-nav-1" class="products-slick-nav"></div>
                        </div>
                        <!-- /tab -->
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}