app/cart/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views


app_name = 'cart'


urlpatterns = [
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/order/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views




app_name = 'order'


urlpatterns = [
    path('create/', views.ViewCreateOrder.as_view(), name='create_order'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views


app_name = 'shop'


urlpatterns = [
    path('', views.ViewProductList.as_view(), name='product_list'),
    path('<int:id>/<slug:slug>/', views.ViewProductDetail.as_view(), name='product_detail'),
    path('<int:id>/<slug:slug>/comments/<int:page_num>/', views.ViewCreateProductComment.as_view(), name='product_comment'),
    path('store/', views.ViewProductListForCategory.as_view(), name='store'),
    path('store/filter/', views.ViewFilterProductList.as_view(), name='filter_store'),
    path('store/search', views.ViewSearchProductList.as_view(), name='search_product')
]




if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('order/', include('order.urls', namespace='order')),
    path('account/', include('account.urls', namespace='account')),
    path('wishlist/', include('wishlist.urls', namespace='wishlist'))
]

app/wishlist/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views


app_name = 'wishlist'


urlpatterns = [
    path('', views.ViewWishList.as_view(), name='wishlist'),
    path('add/<int:product_id>', views.WishlistCreate.as_view(), name='wishlist_add'),
    path('remove/<int:product_id>', views.WishlistDelete.as_view(), name='wishlist_remove')
]




if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/shop/models.py
from django.db import models
from django.shortcuts import get_object_or_404
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(upload_to=f'category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'category/{self.name}'


class Brand(models.Model):
    name = models.CharField(max_length=50, db_index=True)

    def __str__(self):
        return self.name


class Ip(models.Model):
    ip = models.CharField(max_length=100)

    def __str__(self):
        return self.ip


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    brand = models.ForeignKey(Brand,
                              related_name='brands', null=True,
                              on_delete=models.SET_NULL)
    image = models.ImageField(upload_to='products', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    ip_view = models.ManyToManyField(Ip, related_name="post_views", blank=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

    @property
    def get_rating(self):
        product = get_object_or_404(Product, id=self.id, available=True)
        comments = product.comments.filter(active=True)
        rating_list = [comment.rating for comment in comments]
        rating = round(sum(rating_list) / len(comments), 1)
        return rating

    @property
    def total_views(self):
        return self.ip_view.count()


class Gallery(models.Model):
    image = models.ImageField(upload_to='gallery')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')


class Comment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    rating = models.IntegerField(default=0)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.product)

app/shop/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, HTML
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    name = forms.CharField(label='Name',
                           widget=forms.TextInput(attrs={'class': 'input', 'type': 'text', 'placeholder': "Your Name"}))
    email = forms.CharField(label='Email', widget=forms.TextInput(
        attrs={'class': 'input', 'type': 'email', 'placeholder': "Your Email"}))
    body = forms.CharField(label='Body', widget=forms.Textarea(attrs={'class': 'input', 'placeholder': "Your Review"}))
    rating = forms.IntegerField(min_value=0, max_value=5)

    class Meta:
        model = Comment
        fields = ('name', 'email', 'body', 'rating')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            'name',
            'email',
            'body',
            Div(HTML('<span>Your Rating: </span>'
                     '<div class="stars">'
                     '<input id="star5" name="rating" value=5 type="radio"><label for="star5"></label>'
                     '<input id="star4" name="rating" value=4 type="radio"><label for="star4"></label>'
                     '<input id="star3" name="rating" value=3 type="radio"><label for="star3"></label>'
                     '<input id="star2" name="rating" value=2 type="radio"><label for="star2"></label>'
                     '<input id="star1" name="rating" value=1 type="radio"><label for="star1"></label>'
                     '</div>'
                     '{% csrf_token %}'
                     '<button class="primary-btn">Submit</button>'),
                css_class='input-rating'
                ))

app/shop/views.py
from collections import Counter

from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import FormView, ListView, DetailView

from cart.forms import CartAddProductForm
from .forms import CommentForm
from .models import Category, Product, Gallery, Comment, Brand
from .services import add_view_product


class GetCategoryBrand:

    def get_category(self):
        return Category.objects.all()

    def get_brand(self):
        return Brand.objects.all()


class ViewProductList(ListView):
    template_name = 'shop/product_detail/index.html'
    model = Product

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['cart_product_form'] = CartAddProductForm()
        return context

    def get_queryset(self):
        return Product.objects.filter(available=True)


class ViewProductDetail(DetailView):
    template_name = 'shop/product_detail/detail.html'
    model = Product

    @method_decorator(add_view_product)
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        kwargs = self.kwargs
        context['cart_product_form'] = CartAddProductForm()
        context['product'] = get_object_or_404(Product, id=kwargs['id'], slug=kwargs['slug'], available=True)
        context['gallery'] = Gallery.objects.filter(product=kwargs['id'])
        context['comments'] = context['product'].comments.filter(active=True)
        context['request'] = self.request
        return context


class ViewCreateProductComment(FormView):
    template_name = 'shop/product_detail/comments.html'
    form_class = CommentForm
    paginate_by = 5
    model = Comment

    def get_context_data(self, **kwargs):
        context = super(ViewCreateProductComment, self).get_context_data(**kwargs)
        kwargs = self.kwargs
        context['id'] = kwargs['id']
        context['page_num'] = kwargs['page_num']
        context['slug'] = kwargs['slug']
        context['product'] = get_object_or_404(Product, id=context['id'], slug=context['slug'], available=True)
        comments_list = context['product'].comments.filter(active=True)
        paginator = Paginator(comments_list, self.paginate_by)
        page = paginator.get_page(kwargs['page_num'])
        context['page'] = page
        context['comments_list'] = page.object_list
        context['gallery'] = Gallery.objects.filter(product=context['id'])
        context['rating_comments'] = [comment.rating for comment in comments_list]
        try:
            context['average_rating'] = round(sum(context['rating_comments']) / len(comments_list), 1)
        except ZeroDivisionError:
            context['average_rating'] = 0
        context['len_comments_list'] = len(comments_list)
        context['rating_comments'] = Counter(context['rating_comments'])
        return context

    def form_valid(self, form):
        new_comment = form.save(commit=False)
        context = self.get_context_data()
        new_comment.product_id = context['id']
        product = context['product']
        new_comment.post = product
        new_comment.save()
        return super().form_valid(form)

    def get_form(self, form_class=None):
        self.object = super().get_form(form_class)
        return self.object

    def get_success_url(self):
        context = self.get_context_data()
        return reverse('shop:product_comment', kwargs={'id': context['id'], 'slug': context['slug'], 'page_num': 1})


class ViewProductListForCategory(GetCategoryBrand, ListView):
    template_name = 'shop/store.html'
    model = Product
    paginate_by = 9

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        return context

    def get_queryset(self):
        return Product.objects.filter(available=True)


class ViewFilterProductList(ViewProductListForCategory):

    def get_queryset(self):
        price_min = self.request.GET.get('price-min')
        price_max = self.request.GET.get('price-max')
        return Product.objects.filter(Q(category__name__in=self.request.GET.getlist('category')) |
                                      Q(brand__name__in=self.request.GET.getlist('brand'))).filter(price__range=(price_min, price_max))


class ViewSearchProductList(ListView):
    template_name = 'shop/search.html'
    model = Product

    def get_queryset(self):
        if self.request.GET.get('category') == 'all':
            return Product.objects.filter(name__icontains=self.request.GET.get('product'))
        return Product.objects.filter(Q(category__name__in=self.request.GET.get('category')) |
                                      Q(name__icontains=self.request.GET.get('product')))

app/shop/templates/shop/checkout.html
{% extends "shop/base.html" %}
{% load static %}
{% block content %}
		<!-- BREADCRUMB -->
		<div id="breadcrumb" class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-12">
						<h3 class="breadcrumb-header">Checkout</h3>
						<ul class="breadcrumb-tree">
							<li><a href="#">Home</a></li>
							<li class="active">Checkout</li>
						</ul>
					</div>
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /BREADCRUMB -->

		<!-- SECTION -->
		<div class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">

					<div class="col-md-7">
						<!-- Billing Details -->
                        <form action="{% url "order:create_order" %}" method='post'>
						<div class="billing-details" >
							<div class="section-title">
								<h3 class="title">Billing address</h3>
							</div>
                            {{ order_form.as_p }}
							<div class="order-notes">
							<textarea class="input" placeholder="Order Notes"></textarea>
                            </div>
                            {% csrf_token %}
                            <button class="primary-btn order-submit">Place order</button>
						</div>
                        </form>
						<!-- /Billing Details -->

					</div>

					<!-- Order Details -->
					<div class="col-md-5 order-details">
						<div class="section-title text-center">
							<h3 class="title">Your Order</h3>
						</div>
						<div class="order-summary">
							<div class="order-col">
								<div><strong>PRODUCT</strong></div>
								<div><strong>TOTAL</strong></div>
							</div>
							<div class="order-products">
                                {% for item_product in cart %}
								<div class="order-col">
									<div>{{ item_product.quantity }}x {{ item_product.product.name }}</div>
									<div>$980.00</div>
								</div>
                                {% endfor %}
							</div>
							<div class="order-col">
								<div>Shiping</div>
								<div><strong>FREE</strong></div>
							</div>
							<div class="order-col">
								<div><strong>TOTAL</strong></div>
								<div><strong class="order-total">{{cart.get_total_price}}</strong></div>
							</div>
						</div>
						<div class="payment-method">
							<div class="input-radio">
								<input type="radio" name="payment" id="payment-1">
								<label for="payment-1">
									<span></span>
									Direct Bank Transfer
								</label>
								<div class="caption">
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
								</div>
							</div>
							<div class="input-radio">
								<input type="radio" name="payment" id="payment-2">
								<label for="payment-2">
									<span></span>
									Cheque Payment
								</label>
								<div class="caption">
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
								</div>
							</div>
							<div class="input-radio">
								<input type="radio" name="payment" id="payment-3">
								<label for="payment-3">
									<span></span>
									Paypal System
								</label>
								<div class="caption">
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
								</div>
							</div>
						</div>
						<div class="input-checkbox">
							<input type="checkbox" id="terms">
							<label for="terms">
								<span></span>
								I've read and accept the <a href="#">terms & conditions</a>
							</label>
						</div>
					</div>
					<!-- /Order Details -->

				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /SECTION -->
{% endblock %}

app/shop/templates/shop/search.html
{% extends "shop/base.html" %}
{% load static %}
{% block content %}
    <div class="section">
        <!-- container -->
        <div class="container">
            <!-- row -->
            <div class="row">

                <!-- section title -->
                <div class="col-md-12">
                    <div class="section-title">
                        <h3 class="title">Searching results</h3>
                    </div>
                </div>
                <!-- /section title -->
                <!-- Products tab & slick -->
                <div class="col-md-12">
                    <div class="row">
                        <div class="products-tabs">
                            <!-- tab -->
                            <div id="tab1" class="tab-pane active">
                                <div class="products-slick" data-nav="#slick-nav-1">
                                    <!-- product -->
                                    {% for product in object_list %}
                                        <div class="product">
                                            <div class="product-img">
                                                <img src="{{ product.image.url }}" alt="" class="Image">
                                                <div class="product-label">
                                                    <span class="sale">-30%</span>
                                                    <span class="new">NEW</span>
                                                </div>
                                            </div>
                                            <div class="product-body">
                                                <p class="product-category">{{ product.catecory }}</p>
                                                <h3 class="product-name"><a
                                                        href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                                                </h3>
                                                <h4 class="product-price">{{ product.price }}
                                                    <div class="product-old-price">$990.00</div>
                                                </h4>
                                                <div class="product-rating">
                                                    {% if product.get_rating >= 1 %}
                                                        <i class="fa fa-star"></i>
                                                    {% else %}
                                                        <i class="fa fa-star-o empty"></i>
                                                    {% endif %}
                                                    {% if product.get_rating >= 2 %}
                                                        <i class="fa fa-star"></i>
                                                    {% else %}
                                                        <i class="fa fa-star-o empty"></i>
                                                    {% endif %}
                                                    {% if product.get_rating >= 3 %}
                                                        <i class="fa fa-star"></i>
                                                    {% else %}
                                                        <i class="fa fa-star-o empty"></i>
                                                    {% endif %}
                                                    {% if product.get_rating >= 4 %}
                                                        <i class="fa fa-star"></i>
                                                    {% else %}
                                                        <i class="fa fa-star-o empty"></i>
                                                    {% endif %}
                                                    {% if product.get_rating == 5 %}
                                                        <i class="fa fa-star"></i>
                                                    {% else %}
                                                        <i class="fa fa-star-o empty"></i>
                                                    {% endif %}
                                                </div>
                                                <div class="product-btns">
                                                    <form action="{% url 'wishlist:wishlist_add' product.id %}"
                                                          method="post">
                                                        {% csrf_token %}
                                                        <button class="add-to-wishlist"><i
                                                                class="fa fa-heart-o"></i><span
                                                                class="tooltipp">add to wishlist</span></button>
                                                    </form>
                                                    <button class="add-to-compare"><i class="fa fa-exchange"></i><span
                                                            class="tooltipp">add to compare</span></button>
                                                    <button class="quick-view"><i class="fa fa-eye"></i><span
                                                            class="tooltipp">quick view</span>
                                                    </button>
                                                </div>
                                            </div>
                                            <div class="add-to-cart">
                                                <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                                    {{ cart_product_form }}
                                                    {% csrf_token %}
                                                    <button class="add-to-cart-btn">Add<i
                                                            class="fa fa-shopping-cart"></i>
                                                    </button>
                                                </form>
                                            </div>
                                        </div>
                                    {% endfor %}
                                    <!-- /product -->
                                </div>
                                <div id="slick-nav-1" class="products-slick-nav"></div>
                            </div>
                            <!-- /tab -->
                        </div>
                    </div>
                </div>
                <!-- Products tab & slick -->
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
{% endblock %}

app/shop/templates/shop/store.html
{% extends "shop/base.html" %}
{% load static %}
{% block content %}
<div class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<!-- ASIDE -->
					<div id="aside" class="col-md-3">
                    <form action="{% url 'shop:filter_store' %}" method="get">
						<!-- aside Widget -->
						<div class="aside">
							<h3 class="aside-title">Categories</h3>
							<div class="checkbox-filter">
                                {% for category in view.get_category %}
								<div class="input-checkbox">
									<input type="checkbox" id="{{ category.name }}" name="category" value="{{ category.name }}">
									<label for="{{ category.name }}">
										<span></span>
                                        {{ category.name }}
										<small>(120)</small>
									</label>
								</div>
                                {% endfor %}

							</div>
						</div>
						<!-- /aside Widget -->

						<!-- aside Widget -->
						<div class="aside">
							<h3 class="aside-title">Price</h3>
							<div class="price-filter">
								<div id="price-slider"></div>
								<div class="input-number price-min">
									<input id="price-min" type="number" name="price-min">
									<span class="qty-up">+</span>
									<span class="qty-down">-</span>
								</div>
								<span>-</span>
								<div class="input-number price-max">
									<input id="price-max" type="number" name="price-max">
									<span class="qty-up">+</span>
									<span class="qty-down">-</span>
								</div>
							</div>
						</div>
						<!-- /aside Widget -->

						<!-- aside Widget -->
						<div class="aside">
							<h3 class="aside-title">Brand</h3>
							<div class="checkbox-filter">
                                {% for brand in view.get_brand %}
								<div class="input-checkbox">
									<input type="checkbox" id="{{ brand.name }}" name="brand" value="{{ brand.name }}">
									<label for="{{ brand.name }}">
										<span></span>
                                        {{ brand.name }}
										<small>(578)</small>
									</label>
								</div>
                                {% endfor %}
							</div>
						</div>
						<!-- /aside Widget -->
                    <button class="primary-btn">Поиск</button>
                    </form>
						<!-- aside Widget -->
						<div class="aside">
							<h3 class="aside-title">Top selling</h3>
							<div class="product-widget">
								<div class="product-img">
									<img src="../../static/img/product01.png" alt="">
								</div>
								<div class="product-body">
									<p class="product-category">Category</p>
									<h3 class="product-name"><a href="#">product name goes here</a></h3>
									<h4 class="product-price">$980.00 <del class="product-old-price">$990.00</del></h4>
								</div>
							</div>

							<div class="product-widget">
								<div class="product-img">
									<img src="../../static/img/product02.png" alt="">
								</div>
								<div class="product-body">
									<p class="product-category">Category</p>
									<h3 class="product-name"><a href="#">product name goes here</a></h3>
									<h4 class="product-price">$980.00 <del class="product-old-price">$990.00</del></h4>
								</div>
							</div>

							<div class="product-widget">
								<div class="product-img">
									<img src="../../static/img/product03.png" alt="">
								</div>
								<div class="product-body">
									<p class="product-category">Category</p>
									<h3 class="product-name"><a href="#">product name goes here</a></h3>
									<h4 class="product-price">$980.00 <del class="product-old-price">$990.00</del></h4>
								</div>
							</div>
						</div>
						<!-- /aside Widget -->
					</div>
					<!-- /ASIDE -->

					<!-- STORE -->
					<div id="store" class="col-md-9">
						<!-- store top filter -->
						<div class="store-filter clearfix">
							<div class="store-sort">
								<label>
									Sort By:
									<select class="input-select">
										<option value="0">Popular</option>
										<option value="1">Position</option>
									</select>
								</label>

								<label>
									Show:
									<select class="input-select">
										<option value="0">20</option>
										<option value="1">50</option>
									</select>
								</label>
							</div>
							<ul class="store-grid">
								<li class="active"><i class="fa fa-th"></i></li>
								<li><a href="#"><i class="fa fa-th-list"></i></a></li>
							</ul>
						</div>
						<!-- /store top filter -->

						<!-- store products -->
						<div class="row">
                            {% for product in object_list %}
							<!-- product -->
							<div class="col-md-4 col-xs-6">
								<div class="product">
									<div class="product-img">
										<img src="{{ product.image.url }}" alt="">
										<div class="product-label">
											<span class="sale">-30%</span>
											<span class="new">NEW</span>
										</div>
									</div>
									<div class="product-body">
										<p class="product-category">{{ product.category }}</p>
										<h3 class="product-name"><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h3>
										<h4 class="product-price">{{ product.price }} <del class="product-old-price">$990.00</del></h4>
										<div class="product-rating">
                                                    {% if product.get_rating >= 1  %}
                                                        <i class="fa fa-star"></i>
                                                    {% else %}
                                                        <i class="fa fa-star-o empty"></i>
                                                    {% endif %}
                                                    {% if product.get_rating >= 2  %}
                                                        <i class="fa fa-star"></i>
                                                    {% else %}
                                                        <i class="fa fa-star-o empty"></i>
                                                    {% endif %}
                                                    {% if product.get_rating >= 3 %}
                                                        <i class="fa fa-star"></i>
                                                    {% else %}
                                                        <i class="fa fa-star-o empty"></i>
                                                    {% endif %}
                                                    {% if product.get_rating >= 4 %}
                                                        <i class="fa fa-star"></i>
                                                    {% else %}
                                                        <i class="fa fa-star-o empty"></i>
                                                    {% endif %}
                                                    {% if product.get_rating == 5 %}
                                                        <i class="fa fa-star"></i>
                                                    {% else %}
                                                        <i class="fa fa-star-o empty"></i>
                                                    {% endif %}
										</div>
										<div class="product-btns">
											<button class="add-to-wishlist"><i class="fa fa-heart-o"></i><span class="tooltipp">add to wishlist</span></button>
											<button class="add-to-compare"><i class="fa fa-exchange"></i><span class="tooltipp">add to compare</span></button>
											<button class="quick-view"><i class="fa fa-eye"></i><span class="tooltipp">quick view</span></button>
										</div>
									</div>
									<div class="add-to-cart">
										<button class="add-to-cart-btn"><i class="fa fa-shopping-cart"></i> add to cart</button>
									</div>
								</div>
							</div>
							<!-- /product -->
                            {% endfor %}

						</div>
						<!-- /store products -->

						<!-- store bottom filter -->
						<div class="store-filter clearfix">
							<span class="store-qty">Showing 20-100 products</span>
							<ul class="store-pagination">
								<li class="active">1</li>
								<li><a href="#">2</a></li>
								<li><a href="#">3</a></li>
								<li><a href="#">4</a></li>
								<li><a href="#"><i class="fa fa-angle-right"></i></a></li>
							</ul>
						</div>
						<!-- /store bottom filter -->
					</div>
					<!-- /STORE -->
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
{% endblock %}